services:
  postgres:
    image: postgres:17
    container_name: uaimed_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: uaimed
    ports:
      - "5432:5432"
      